# This file should be included by Makefiles of executables that want to
# use the unicorn library

CFLAGS  = `pkg-config --cflags dolfin`
LIBS    = `pkg-config --libs dolfin`
CXX     = `pkg-config --variable=compiler dolfin` -g -std=c++11

FFCFLAGS = -O -r quadrature -fsplit -l dolfin

%.cpp: %.ufl
	cd $(LIBDIR)/ufc2 && ffc $(FFCFLAGS) $(notdir $<)

UFC2OBJECTS = $(LIBDIR)/ufc2/NSEMomentum3D.o $(LIBDIR)/ufc2/NSEContinuity3D.o $(LIBDIR)/ufc2/NSEDualMomentum3D.o $(LIBDIR)/ufc2/NSEDualContinuity3D.o $(LIBDIR)/ufc2/NSEErrRepMomentum3D.o $(LIBDIR)/ufc2/NSEErrRepContinuity3D.o $(LIBDIR)/ufc2/Drag3D.o $(LIBDIR)/ufc2/NSEH1.o $(LIBDIR)/ufc2/NSEH12.o $(LIBDIR)/ufc2/NSEErrEst.o $(LIBDIR)/ufc2/NSEErrEstGlobal.o $(LIBDIR)/ufc2/NSEMomentumResidual3D.o $(LIBDIR)/ufc2/NSEContinuityResidual3D.o $(LIBDIR)/ufc2/NSEMomentumResidualGlobal3D.o $(LIBDIR)/ufc2/NSEContinuityResidualGlobal3D.o $(LIBDIR)/ufc2/NSEH1Momentum3D.o $(LIBDIR)/ufc2/NSEH1Continuity3D.o $(LIBDIR)/ufc2/NSEH1MomentumGlobal3D.o $(LIBDIR)/ufc2/NSEH1ContinuityGlobal3D.o
LIBOBJECTS = $(LIBDIR)/NodeNormal.o $(LIBDIR)/SpaceTimeFunction.o $(LIBDIR)/SlipBC.o 

cleanLib:
	-rm -f *.o core *.core $(OBJECTS) $(DEST)
	for i in $(UFC2OBJECTS) ; do \
    rm -f $$i "$${i%.o}.cpp" "$${i%.o}.h" ; \
    done

.cpp.o:
	$(CXX) $(CFLAGS) -c $< -o $@
